name: Update streak stats

on:
  schedule:
    - cron: "0 3 * * *" # Run every day at 03:00
  push:
    paths:
      - ".github/workflows/streak-stats.yml" # Run any time this file is modified
  workflow_dispatch: # Run manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate personal streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=omidnw&theme=onedark&disable_animations=true
          path: profile/streak-omidnw.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate work streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=omidrezakeshtkar&theme=onedark&disable_animations=true
          path: profile/streak-omidrezakeshtkar.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak-omidnw.svg profile/streak-omidrezakeshtkar.svg
          git commit -m "chore: update streak stats" || exit 0
          git push